### ISSUE TITLE
Design Docs #1

### ISSUE THREAD

**Issue by rlim92** [isaac-owens/Sosofly#1]
Hey Isaac! Everything is looking good so far. Some tips below. 

**MVP List**
- [x] for bonus, consider adding auto-fill and/or debouncing for search later. 

**Schema**
- [x] add `profile_name`/`username`, `birthdate`, and `gender` columns. Spotify has those columns as well in their sign up form.
- [x] `playlist` table `image_url` column is not needed. Use AWS for photo hosting. 
- [x] `followable` and `likeable` cannot be a column for any of the tables in the schema. Instead, make a `likes` joins tables that is also polymorphic (in that, a like joins a user to one of many options: [`playlists`, `albums`, `tracks`]). This is because a user can like many `playlists`, `albums` and `tracks` and all of those can have many likes from different `users`. The `follows` table just needs to be a classic many-to-many joins joining `users` and `artists`. 
- [x] for `tracks` table they should not belong to just one `playlist_id`. This also needs a joins table joining `tracks` and `playlists` to achieve a many-to-many relationship.

**Comment by rlim92** [comment]
just a reminder, i added a bullet point after looking at the sign up form

**Comment by isaac-owens** [comment]
Ah yes, I was looking for that bullet earlier.  I’ll make sure to add them to my table.  I was thinking  since this info is never displayed/used for the life of my app it would be extraneous.

**Comment by isaac-owens** [comment]
All up to date on issues!  I'm still a bit confused about design doc structure.  It seems like the Web Player (which you can get to and use logged in or logged out) is completely separate of the login, logout, and splash pages.  In those cases I don't have any fixed components on the page.  So should I not be counting my components from the Web Player as components that are always displayed?

**Comment by rlim92** [comment]
Yeah it does look like you can reach the web player not logged in and as soon as you click on certain features it requires a login. I think you can have the webplayer render no matter if you're logged in or not but you will need some ProtectedRoutes that can only be reached if logged in and then some AuthRoutes that render instead of the ProtectedRoutes if not logged in.

**Comment by isaac-owens** [comment]
Hey Rich I got strikes for lunch and afternoon today but I was there.  Was there something wrong with today being the first day for breakout rooms?

Isaac Owens
214–316-3699
