### ISSUE TITLE
Design Docs Sample State Review

### ISSUE THREAD

**Issue by rlim92** [isaac-owens/Sosofly#2]
Hey Isaac! Sample state looking good. Some suggestions below.

**Sample State**
- [x] for `users` only pull the array data (basically all the liked/followed/playlist data) only for user show page. Reason being the data is not necessary until we pretty much click on the user to see what content they consume/create. 
- [x] make sure `playlists` has a key for `trackIds`. 
- [x] add a key of `path` or `url` to `tracks` that would indicate the secure url to AWS audio hosting for that specific track.
- [x] add `albumIds` as a key to `artists` slice of state.
- [x] add `likerIds` as a key to `albums` slice of state.

**Comment by isaac-owens** [comment]
Hi Rich

I’m not quite sure what you mean in regards to your first note.  Can you clarify?

**Comment by rlim92** [comment]
Hey Isaac, 

So basically we'll probably be pulling users w/ an index type action for things like `followers` or `likers` of a playlist. When we pull that data, we really just want like simple information like their `name` only. After a click on the user to get to their show page, thats when we want to grab the extra information. Very similar to `PokemonDetail` vs `PokemonIndex`.
