### ISSUE TITLE
Design Docs #3

### ISSUE THREAD

**Issue by rlim92** [isaac-owens/Sosofly#3]
Hey Isaac! Well thought out routes. Some suggestions below:

**Frontend Routes**
- [x] make sure frontend routes are camelCased
- [x] when not logged in you are shown a splash page, just make sure to have `/` render a Splash when not logged in. 
- [x] the `/signup` and `/login` can both render the same `SessionForm` but with a different container (makes it more dry). 
- [x] the website seems to redirect to a general Splash after login and then you can open the web player. Might want to add that as the `/` route for logged in and then have a `/webplayer` or something named differently that renders the web player.
- [x] for `/genre/:categoryId` make sure `Genre` is a show component and is rendering some type of track index for that genre
- [x] for `/search` specify what `Genre` component is rendered (should be an index).

**Backend Routes**
- [x] `DELETE /api/playlists` needs a wildcard id to know which playlist to delete

**Comment by isaac-owens** [comment]
Hey Rich!  I was treating the webplayer 'open.spotify.com' as my root/home page.  Are you saying that I should be starting with spotify.com as my root/home page?  The page with the subscription options on it?  I think we may be looking at diff pages.  Is there some time we could screen share and make sure we're on the same page?

**Comment by rlim92** [comment]
Hey Isaac! we spoke over Slack but yeah make sure to have spotify.com as the home page and then have a link to the webplayer upon login/signup.

**Comment by isaac-owens** [comment]
Gotcha crystal clear.  I’ll do some shifting around with my docs today/tonight.  This is fun!  Feels like I’m really working 🙃

Isaac Owens
214–316-3699
