### ISSUE TITLE
Review for auth

### ISSUE THREAD

**Issue by isaac-owens** [isaac-owens/Sosofly#4]
I fixed the splash page hero image and fixed styling on all of my forms.  I'd like to start working on that dropdown menu on the account profile page

**Comment by rlim92** [comment]
Hey Isaac! Site is looking fly so far. Some differences: 
- [ ] the color of the borders for the inputs in the sign up form are different
- [ ] the birthdate portion has 3 different inputs for month/day/year on the real website.
- [ ] on hover of the `sign up` button it moves the elements below it some pixels down. Make sure it doesn't move the elements below it down. 
- [ ] for the sign in page, there should be a border below the logo 
- [ ] make sure the message of `Please enter..` are only shown after attempting to log in. 
- [ ] the errors for the sign up form should have a small exclamation point wrapped in a circle similar to the real site.

Really good work so far!

**Comment by isaac-owens** [comment]
Hey Rich!  I've fixed quite a few things and started out on the webplayer.  It's quite static right now but this is just the basic layout before adding all of the dynamic React action to it.  All of the working links on the site are connected so you can navigate from one page to the other.  I'll keep fine tuning those forms.  I started in on the playlist slice of state this weekend and have all of my CRUD actions working. 

[https://sosofly.herokuapp.com/#/](url)
